# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Fire2aSimulator
                                 A QGIS plugin
 Simulate wildfires, forestfires easily. Check your landscape plan valuation under multiple fire scenarios and get insightful risk metrics, analytics and more! From a combustion layer, to crown fire, weather behavior, etc.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-06
        copyright            : (C) 2023 by Fernando Badilla Veliz - Fire2a
        email                : fbadilla@ing.uchile.cl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Fire2aSimulator class from file Fire2aSimulator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cell2fire2asimulator import Fire2aSimulator
    return Fire2aSimulator(iface)
